"""initial

Revision ID: bb9f5c198228
Revises: 247d48ef93fa
Create Date: 2025-09-14 22:44:54.269836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9f5c198228'
down_revision: Union[str, Sequence[str], None] = '247d48ef93fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'user',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('email', sa.String(255), nullable=False, unique=True),
        sa.Column('password_hash', sa.String(255), nullable=False),
        sa.Column('role', sa.Enum('ADMIN', 'AGENT', name='roleenum'), nullable=False, server_default='AGENT'),
        sa.Column('created', sa.DateTime, server_default=sa.func.getutcdate()),
    )

    op.create_table(
        'notes',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('user.id'), nullable=False),
        sa.Column('raw_text', sa.Text, nullable=False),
        sa.Column('summary', sa.Text),
        sa.Column('status', sa.Enum('queued', 'processing', 'done', 'failed', name='notestatus'), nullable=False, server_default='queued'),
        sa.Column('retries', sa.Integer, nullable=False, server_default='0'),
        sa.Column('max_retries', sa.Integer, nullable=False, server_default='3'),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.getutcdate()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.getutcdate()),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
